version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: websec
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./app/websec.sql:/docker-entrypoint-initdb.d/websec.sql
    ports:
      - "3306:3306"

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
